// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBf04bHFXh-_zy29qHPvH4nctHvZ0JNQ',
    appId: '1:769896560673:web:7b0978d56dda05ce35cb60',
    messagingSenderId: '769896560673',
    projectId: 'push-notification-9014f',
    authDomain: 'push-notification-9014f.firebaseapp.com',
    storageBucket: 'push-notification-9014f.firebasestorage.app',
    measurementId: 'G-SQWYPTSTNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKzJaZ80OrlWghiQghP8Ae0-VKd1pDwo',
    appId: '1:769896560673:android:bf4c7fee11443a8a35cb60',
    messagingSenderId: '769896560673',
    projectId: 'push-notification-9014f',
    storageBucket: 'push-notification-9014f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCreTvSHonwBkLJWGeg_juU5fkimUaM8TA',
    appId: '1:769896560673:ios:98b7bc6ae54d962435cb60',
    messagingSenderId: '769896560673',
    projectId: 'push-notification-9014f',
    storageBucket: 'push-notification-9014f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCreTvSHonwBkLJWGeg_juU5fkimUaM8TA',
    appId: '1:769896560673:ios:98b7bc6ae54d962435cb60',
    messagingSenderId: '769896560673',
    projectId: 'push-notification-9014f',
    storageBucket: 'push-notification-9014f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBf04bHFXh-_zy29qHPvH4nctHvZ0JNQ',
    appId: '1:769896560673:web:c5c8d68eca29b35635cb60',
    messagingSenderId: '769896560673',
    projectId: 'push-notification-9014f',
    authDomain: 'push-notification-9014f.firebaseapp.com',
    storageBucket: 'push-notification-9014f.firebasestorage.app',
    measurementId: 'G-SDEC6C223Y',
  );
}
